<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ConsoleTheme">
      <HintPath>H:\.Net\Projects\ConsoleTheme-master\ConsoleTheme\bin\Debug\net8.0\ConsoleTheme.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
